### ISSUE TITLE
Taichi

### ISSUE THREAD

**Issue by OmidGhotbi** [PavelBlend/Blender-Molecular-Script#10]
can i ask why you ditched Taichi, last time i checked it's worked with C as AOT i tried it and it was quiet good too, because you have more experience with it can i ask you for your professional advice?

**Comment by PavelBlend** [comment]
@OmidGhotbi  I tried to rewrite the kernel in taichi, but it didn't work. Taichi does not support recursion. But kd-tree uses recursion. I do programming in my free time at an amateur level. There are many things I cannot implement.

**Comment by OmidGhotbi** [comment]
thank you.
