### ISSUE TITLE
Update authors

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/Blender-Molecular-Script#17]
@OmidGhotbi I want to add you to the list of addon authors in [bl_info](https://github.com/PavelBlend/blender-molecular/blob/902db6a8e52a7fa36e4617d62aa0ab665c09c6b8/blender/__init__.py#L3). How to write your name?

**Comment by OmidGhotbi** [comment]
Thank you my name is Omid Ghotbi and my email is Omidt.gh@gmail.com if you needed.

**Comment by PavelBlend** [comment]
fecb425064cde53b186619e4b49010b6d6d56deb

**Comment by OmidGhotbi** [comment]
Great, just one modification Omid Ghotbi (TAO)
