### ISSUE TITLE
particle explosion

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/Blender-Molecular-Script#20]
@OmidGhotbi I noticed particle explosions in your last version of the code. Particles fly too far.

https://github.com/PavelBlend/blender-molecular/assets/7983249/411175de-093e-4a31-b53c-df7c3a4ac0b5

Here is an example blend file: 
[untitled.zip](https://github.com/PavelBlend/blender-molecular/files/15226592/untitled.zip)

**Comment by OmidGhotbi** [comment]
I did change equation to get more chaotic results that wasn't possible before. So i may did it a bit to strong. 
this is the compare between two equation. Let me double check the equation and i will get back to you. 

![Molecular-New-Eq](https://github.com/PavelBlend/blender-molecular/assets/164653/21a2b877-a019-4c85-a557-86db10d33e5c)
Left is old EQ and right is new EQ . Both have the same parameters.

**Comment by OmidGhotbi** [comment]
I double-checked the code, it is just more accurate I believe. As it is more sensitive in collisions, it's better to slightly change the parameters. for example, Self-friction of about 0.25 and self-dumping of about 0.15 will solve the issue in your case.
![image](https://github.com/PavelBlend/blender-molecular/assets/164653/d3d2c6e3-e5bc-41f8-afad-9fff4cb005ee)

5 different test cases with your scene in the Zip file below.
[Test.zip](https://github.com/PavelBlend/blender-molecular/files/15240386/Test.zip)

https://github.com/PavelBlend/blender-molecular/assets/164653/a1c6e909-7277-4a3f-a28e-406184cac9d9

**If you still think it's too much let me know and i will change it.**

and here is another test with the new Mesher:

![MesherSDF](https://github.com/PavelBlend/blender-molecular/assets/164653/87eb3e45-1c1a-415d-a590-a7c5e1c863a7)

By the way, I found a bug that can cause a crash during the simulation that I will address soon.
