### ISSUE TITLE
Use the addon

### ISSUE THREAD

**Issue by OmidGhotbi** [PavelBlend/Blender-Molecular-Script#9]
At the moment I'm working on a multiphysics solver and already added the molecular sim to it but I like your approach better, can I add your molecular as well to it?
here is some results of it.

![Screenshot 2024-04-07 184140](https://github.com/PavelBlend/blender-molecular/assets/164653/acc8bfe4-d48f-4cde-ac34-5511fb526feb)

https://github.com/PavelBlend/blender-molecular/assets/164653/6ce3dc32-49b3-4d05-9e07-0857c3e52b56

**Comment by PavelBlend** [comment]
@OmidGhotbi I am not the author of the model from molecular addon. I'm trying to understand the code that @Pyroevil wrote and trying to make edits to it.

There is no license specified in its code:
https://github.com/Pyroevil/Blender-Molecular-Script

So I don't know if this model can be used the way you want.

**Comment by OmidGhotbi** [comment]
from your work is it possible to use it of course with credit or I have to rewrite it ?

**Comment by PavelBlend** [comment]
@OmidGhotbi All algorithms were taken from Pyroevil code. If he doesn't mind, then I can allow the use of my code.

**Comment by PavelBlend** [comment]
> At the moment I'm working on a multiphysics solver and already added the molecular sim

is your program/add-on publicly available?

**Comment by OmidGhotbi** [comment]
i'm at the development stage and trying my best to release the first beta version publically. I believe the MPM solver can do the same or even more but I like to add a molecular solver as well, I've seen the Cython version but I think the C version can be optimized more later.
